### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dblessing** [voxpupuli/puppet-filemapper#11]
This issue is what we talked about in https://github.com/adrienthebo/puppet-network/pull/75

Here's what I know so far. Hopefully this sparks something brilliant because I'm probably not familiar enough with Puppet internals to know what's going on here.

It seems that for each existing resource `new` is being called twice. Below are the caller traces for `new`. One is expected, `instances` because we're calling new explicitly. The one that is not so expected and is actually causing the problem is `provider=`. What happens there is a new resource is created but without many of the properties - one of which is `interface` and is causing the issue in `select_file` for puppet-network.

Any ideas given this info?

```
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1905:in `provider='
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1832:in `unsafe_munge'
/usr/lib/ruby/site_ruby/1.8/puppet/parameter.rb:432:in `munge'
/usr/lib/ruby/site_ruby/1.8/puppet/parameter.rb:502:in `value='
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:817:in `set_default'
/usr/lib/ruby/site_ruby/1.8/puppet/type.rb:2198:in `initialize'
/usr/lib/ruby/site_ruby/1.8/puppet/resource.rb:310:in `new'
/usr/lib/ruby/site_ruby/1.8/puppet/resource.rb:310:in `to_ral'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:501:in `to_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:493:in `each'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:493:in `to_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:395:in `to_ral'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:217:in `main'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:190:in `main'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:151:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:479:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:362:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:4
```

```
/var/lib/puppet/lib/puppetx/filemapper.rb:113:in `instances'
/var/lib/puppet/lib/puppetx/filemapper.rb:111:in `map'
/var/lib/puppet/lib/puppetx/filemapper.rb:111:in `instances'
/var/lib/puppet/lib/puppetx/filemapper.rb:194:in `prefetch'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:277:in `prefetch'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:167:in `prefetch_if_necessary'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:67:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:116:in `traverse'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:108:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:164:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:163:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:125:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:124:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:195:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:288:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:228:in `main'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:190:in `main'
/usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:151:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:479:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:362:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:4
```

**Comment by jyaworski** [comment]
Is this still an issue?

**Comment by oniGino** [comment]
This is till an issue, a very ancient one
```
Notice: /Stage[main]/Profile::Nlb::De/Network_route[internal-ens5]/ensure: created (corrective)
Error: /Stage[main]/Profile::Nlb::De/Network_route[internal-ens5]: Could not evaluate: undefined method `[]' for nil:NilClass
/opt/puppetlabs/puppet/cache/lib/puppet/provider/network_route/redhat.rb:22:in `select_file'
/opt/puppetlabs/puppet/cache/lib/puppetx/filemapper.rb:236:in `block in collect_providers_for_file'
/opt/puppetlabs/puppet/cache/lib/puppetx/filemapper.rb:235:in `select'
/opt/puppetlabs/puppet/cache/lib/puppetx/filemapper.rb:235:in `collect_providers_for_file'
/opt/puppetlabs/puppet/cache/lib/puppetx/filemapper.rb:265:in `flush_file'
/opt/puppetlabs/puppet/cache/lib/puppetx/filemapper.rb:44:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1022:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:25:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:267:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:287:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:555:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:554:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:191:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:122:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:178:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:238:in `block (2 levels) in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:555:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:554:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:237:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:165:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:150:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:236:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:286:in `block (2 levels) in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:555:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:554:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:285:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:233:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:232:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:284:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:500:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:339:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:60:in `block (5 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/opt/puppetlabs/puppet/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:59:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:53:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:136:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:50:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:101:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:49:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:172:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:437:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:397:in `block in run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:302:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:393:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:744:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```
